FROM python:3.11
EXPOSE 8000
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./

CMD [ "python", "-u", "./main.py" ]
# la -u è per mostrare i print nel log (UNBUFFERED=1)